apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DarkinSideNet/DevOps_Projects.git
    targetRevision: main
    path: charts/argo-workflows
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    name: in-cluster
    namespace: argo-workflows
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
